import gzip
import importlib.util
import io
import json
import re
import shlex
import tarfile
import tempfile
import tomllib
import unittest
from argparse import Namespace
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "castlabs_live_video_qualification.py"
WORKFLOW = ROOT / ".github" / "workflows" / "castlabs-live-video-qualification.yml"
QUALIFICATION_DOC = ROOT / "docs" / "castlabs-live-video-qualification.md"
EXPERIMENTAL_DOC = ROOT / "docs" / "experimental-features.md"
SPEC = importlib.util.spec_from_file_location("qualification", SCRIPT)
qualification = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(qualification)


def _valid_header_bytes() -> bytes:
    version = qualification.workspace_version(ROOT / "Cargo.toml")
    declarations = "\n".join(
        f"C2PA_API extern int {symbol}(void);"
        for symbol in qualification.REQUIRED_SYMBOLS
    )
    return (
        "// This file is generated by cbindgen. Do not edit by hand.\n"
        f"// Version: {version}\n"
        f"{declarations}\n"
    ).encode("utf-8")


def _write_qualification_inputs(root: Path, target: str) -> dict[str, Path]:
    paths = {
        "sdk": root / "sdk-features.txt",
        "ffi": root / "ffi-features.txt",
        "tool_features": root / "c2patool-features.txt",
    }
    for name, path in paths.items():
        path.write_bytes(f"{target}:{name}\n".encode("ascii"))
    for logical_name, spec in qualification.TARGET_ARTIFACT_SPECS[target].items():
        path = root / spec["fileName"]
        path.write_bytes(
            _valid_header_bytes()
            if logical_name == "header"
            else f"{target}:{logical_name}\n".encode("ascii")
        )
        paths[logical_name] = path
    command_manifest = root / "cargo-commands.json"
    qualification.write_command_manifest(target, command_manifest)
    paths["command_manifest"] = command_manifest
    return paths


def _evidence_args(
    root: Path,
    lock: Path,
    inputs: dict[str, Path],
    target: str,
    source_sha: str,
    output_name: str = "source-qualification.json",
) -> Namespace:
    output = root / output_name
    return Namespace(
        source_sha=source_sha,
        cargo_lock=str(lock),
        command_manifest=str(inputs["command_manifest"]),
        target=target,
        feature_report=[
            f"c2pa={inputs['sdk']}",
            f"c2pa-c-ffi={inputs['ffi']}",
            f"c2patool={inputs['tool_features']}",
        ],
        artifact=[
            f"{name}={inputs[name]}"
            for name in qualification.TARGET_ARTIFACT_SPECS[target]
        ],
        runner_os="Linux" if "linux" in target else "Windows",
        runner_arch="X64",
        runner_name="test-runner",
        runner_image="test-image",
        output=str(output),
        sha256_output=f"{output}.sha256",
    )


def _build_platform_bundle(
    release_dir: Path,
    work_root: Path,
    lock: Path,
    target: str,
    source_sha: str,
    omit_artifact: str | None = None,
) -> Path:
    work = work_root / target
    work.mkdir(parents=True)
    inputs = _write_qualification_inputs(work, target)
    evidence_args = _evidence_args(work, lock, inputs, target, source_sha)
    qualification.build_evidence(evidence_args)
    evidence = Path(evidence_args.output)
    evidence_sha = Path(evidence_args.sha256_output)
    mappings = [
        f"{inputs[name]}={spec['archivePath']}"
        for name, spec in qualification.TARGET_ARTIFACT_SPECS[target].items()
        if name != omit_artifact
    ]
    mappings.extend(
        (
            f"{evidence}=qualification/source-qualification.json",
            f"{evidence_sha}=qualification/source-qualification.json.sha256",
            f"{inputs['command_manifest']}=qualification/cargo-commands.json",
            f"{inputs['sdk']}=qualification/sdk-features.txt",
            f"{inputs['ffi']}=qualification/ffi-features.txt",
            f"{inputs['tool_features']}=qualification/c2patool-features.txt",
        )
    )
    bundle = release_dir / f"castlabs-c2pa-live-video-{source_sha}-{target}.tar.gz"
    qualification.bundle_from_args(
        Namespace(
            file=mappings,
            output=str(bundle),
            sha256_output=f"{bundle}.sha256",
        )
    )
    return bundle


def _workflow_run_blocks(text: str) -> list[str]:
    lines = text.splitlines()
    blocks = []
    index = 0
    while index < len(lines):
        match = re.match(r"^(\s*)run:\s*(.*)$", lines[index])
        if match is None:
            index += 1
            continue
        indent = len(match.group(1))
        value = match.group(2)
        if value != "|":
            blocks.append(value)
            index += 1
            continue
        index += 1
        block_lines = []
        while index < len(lines):
            line = lines[index]
            if line and len(line) - len(line.lstrip()) <= indent:
                break
            block_lines.append(line)
            index += 1
        blocks.append("\n".join(block_lines))
    return blocks


def _normalized_workflow_cargo_commands(text: str, target: str) -> list[str]:
    replacements = {
        "${{ matrix.target }}": target,
        "${{ env.SDK_FEATURES }}": ",".join(qualification.SDK_FEATURES),
        "${{ env.FFI_FEATURES }}": ",".join(qualification.FFI_FEATURES),
        "${{ env.TOOL_FEATURES }}": ",".join(qualification.TOOL_FEATURES),
        "$SDK_FEATURES": ",".join(qualification.SDK_FEATURES),
        "$FFI_FEATURES": ",".join(qualification.FFI_FEATURES),
        "$TOOL_FEATURES": ",".join(qualification.TOOL_FEATURES),
    }
    commands = []
    for block in _workflow_run_blocks(text):
        for raw_line in block.splitlines():
            line = raw_line.strip()
            if not line.startswith("cargo +"):
                continue
            for source, replacement in replacements.items():
                line = line.replace(source, replacement)
            commands.append(
                f"CARGO_BUILD_JOBS={qualification.CARGO_BUILD_JOBS} "
                + " ".join(shlex.split(line))
            )
    return commands


class BundleTests(unittest.TestCase):
    def test_bundle_is_deterministic_normalized_and_has_no_gzip_filename(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            executable = root / "tool"
            metadata = root / "evidence.json"
            executable.write_bytes(b"tool")
            metadata.write_text("{}\n", encoding="utf-8")
            mappings = (
                (executable, "bin/tool"),
                (metadata, "qualification/evidence.json"),
            )
            one = root / "one.tar.gz"
            two = root / "two.tar.gz"
            qualification.create_bundle(one, mappings)
            qualification.create_bundle(two, tuple(reversed(mappings)))
            self.assertEqual(one.read_bytes(), two.read_bytes())
            self.assertEqual(one.read_bytes()[3] & 0x08, 0)

            with gzip.GzipFile(fileobj=io.BytesIO(one.read_bytes())) as stream:
                with tarfile.open(fileobj=stream, mode="r:") as archive:
                    self.assertEqual(
                        archive.getnames(),
                        ["bin/tool", "qualification/evidence.json", "SHA256SUMS"],
                    )
                    for member in archive.getmembers():
                        self.assertEqual(
                            (member.mtime, member.uid, member.gid), (0, 0, 0)
                        )
                        self.assertEqual((member.uname, member.gname), ("", ""))
                        expected_mode = 0o755 if member.name == "bin/tool" else 0o644
                        self.assertEqual(member.mode, expected_mode)

    def test_import_library_and_header_are_not_marked_executable(self):
        self.assertEqual(qualification._archive_mode("lib/c2pa_c.dll"), 0o755)
        self.assertEqual(qualification._archive_mode("lib/c2pa_c.dll.lib"), 0o644)
        self.assertEqual(qualification._archive_mode("include/c2pa.h"), 0o644)

    def test_rejects_unsafe_duplicate_reserved_and_existing_outputs(self):
        unsafe = ("../escape", "/absolute", "C:/drive", "a\\b", "a//b", "./a")
        for path in unsafe:
            with self.subTest(path=path), self.assertRaises(ValueError):
                qualification.safe_archive_name(path)
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "file"
            source.write_bytes(b"x")
            with self.assertRaises(ValueError):
                qualification.create_bundle(
                    root / "bundle.tar.gz", ((source, "same"), (source, "same"))
                )
            with self.assertRaisesRegex(ValueError, "reserved archive path"):
                qualification.create_bundle(
                    root / "bundle.tar.gz", ((source, "SHA256SUMS"),)
                )
            with self.assertRaises(ValueError):
                qualification.create_bundle(source, ((source, "input"),))
            bundle = root / "new.tar.gz"
            qualification.create_bundle(bundle, ((source, "bin/input"),))
            original = bundle.read_bytes()
            with self.assertRaises(ValueError):
                qualification.create_bundle(bundle, ((source, "bin/input"),))
            self.assertEqual(bundle.read_bytes(), original)


class EvidenceTests(unittest.TestCase):
    def test_command_manifest_is_deterministic_and_rejects_drift(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            one = root / "one" / "cargo-commands.json"
            two = root / "two" / "cargo-commands.json"
            target = "x86_64-unknown-linux-gnu"
            qualification.write_command_manifest(target, one)
            qualification.write_command_manifest(target, two)
            self.assertEqual(one.read_bytes(), two.read_bytes())
            self.assertEqual(
                qualification.load_command_manifest(one, target),
                qualification.cargo_commands(target),
            )
            data = json.loads(one.read_bytes())
            data["commands"].append("cargo unqualified")
            one.write_bytes(qualification._json_bytes(data))
            with self.assertRaisesRegex(ValueError, "does not match"):
                qualification.load_command_manifest(one, target)

    def test_evidence_records_platform_artifacts_roles_and_tool_profiles(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            lock = root / "Cargo.lock"
            lock.write_bytes(b"lock")
            target = "x86_64-pc-windows-msvc"
            inputs = _write_qualification_inputs(root, target)
            first_args = _evidence_args(
                root, lock, inputs, target, "a" * 40, "first.json"
            )
            second_args = _evidence_args(
                root, lock, inputs, target, "a" * 40, "second.json"
            )
            qualification.build_evidence(first_args)
            qualification.build_evidence(second_args)
            first = Path(first_args.output).read_bytes()
            self.assertEqual(first, Path(second_args.output).read_bytes())
            evidence = json.loads(first)
            self.assertEqual(evidence["schemaVersion"], 2)
            self.assertEqual(evidence["python"], {"version": "3.12"})
            self.assertEqual(evidence["rust"]["releaseToolchain"], "1.88.0")
            self.assertEqual(evidence["rust"]["rustfmtToolchain"], "nightly-2026-01-16")
            packages = evidence["qualification"]["packages"]
            self.assertFalse(packages["c2patool"]["noDefaultFeatures"])
            self.assertEqual(
                packages["c2patool"]["requestedFeatures"],
                ["unstable_live_video"],
            )
            self.assertEqual(
                packages["c2patool"]["featureProfile"],
                "default-networking-vendored-openssl",
            )
            commands = evidence["qualification"]["commands"]
            self.assertEqual(commands, qualification.cargo_commands(target))
            self.assertEqual(len(commands), 10)
            self.assertEqual(
                sum(
                    "test --locked --manifest-path cli/Cargo.toml" in item
                    for item in commands
                ),
                1,
            )
            self.assertEqual(
                set(evidence["artifacts"]),
                {"native", "importLibrary", "c2patool", "header"},
            )
            self.assertEqual(
                evidence["artifacts"]["header"]["role"],
                "c-ffi-generated-header",
            )
            self.assertEqual(
                evidence["artifacts"]["importLibrary"]["role"],
                "c-ffi-msvc-import-library",
            )
            self.assertEqual(
                evidence["artifacts"]["header"]["buildPath"],
                f"target/{target}/release/c2pa.h",
            )
            self.assertEqual(
                evidence["qualification"]["commandManifest"]["fileName"],
                "cargo-commands.json",
            )
            with self.assertRaises(ValueError):
                qualification.build_evidence(first_args)
            self.assertEqual(first, Path(first_args.output).read_bytes())

    def test_evidence_rejects_incomplete_artifact_set(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            lock = root / "Cargo.lock"
            lock.write_bytes(b"lock")
            target = "x86_64-pc-windows-msvc"
            inputs = _write_qualification_inputs(root, target)
            args = _evidence_args(root, lock, inputs, target, "b" * 40)
            args.artifact = [
                item for item in args.artifact if not item.startswith("importLibrary=")
            ]
            with self.assertRaisesRegex(ValueError, "missing importLibrary"):
                qualification.build_evidence(args)
            self.assertFalse(Path(args.output).exists())


class ReleaseAssetTests(unittest.TestCase):
    def test_platform_bundles_require_exact_members_and_embedded_evidence(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            release = root / "release"
            release.mkdir()
            lock = root / "Cargo.lock"
            lock.write_bytes(b"lock")
            source_sha = "c" * 40
            bundles = {
                target: _build_platform_bundle(
                    release, root / "work", lock, target, source_sha
                )
                for target in qualification.SUPPORTED_TARGETS
            }
            qualification.verify_release_assets(
                release, source_sha, qualification.SUPPORTED_TARGETS, lock
            )
            linux_files = qualification._archive_files(
                bundles["x86_64-unknown-linux-gnu"]
            )
            windows_files = qualification._archive_files(
                bundles["x86_64-pc-windows-msvc"]
            )
            self.assertIn("include/c2pa.h", linux_files)
            self.assertIn("include/c2pa.h", windows_files)
            self.assertNotIn("lib/c2pa_c.dll.lib", linux_files)
            self.assertIn("lib/c2pa_c.dll.lib", windows_files)

    def test_windows_bundle_without_import_library_is_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            release = root / "release"
            release.mkdir()
            lock = root / "Cargo.lock"
            lock.write_bytes(b"lock")
            source_sha = "d" * 40
            _build_platform_bundle(
                release,
                root / "work",
                lock,
                "x86_64-unknown-linux-gnu",
                source_sha,
            )
            _build_platform_bundle(
                release,
                root / "work",
                lock,
                "x86_64-pc-windows-msvc",
                source_sha,
                omit_artifact="importLibrary",
            )
            with self.assertRaisesRegex(ValueError, "missing artifact"):
                qualification.verify_release_assets(
                    release, source_sha, qualification.SUPPORTED_TARGETS, lock
                )

    def test_release_requires_both_targets_exactly_once(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            lock = root / "Cargo.lock"
            lock.write_bytes(b"lock")
            with self.assertRaisesRegex(
                ValueError, "each supported target exactly once"
            ):
                qualification.verify_release_assets(
                    root,
                    "e" * 40,
                    (qualification.SUPPORTED_TARGETS[0],),
                    lock,
                )


class VerificationTests(unittest.TestCase):
    def test_elf_export_parser_requires_callable_external_definition(self):
        text = """
Symbol table '.dynsym' contains 8 entries:
   Num:    Value          Size Type    Bind   Vis       Ndx Name
     1: 0000000000001000    24 FUNC    GLOBAL DEFAULT    12 c2pa_global
     2: 0000000000001020    24 IFUNC   WEAK   PROTECTED  13 c2pa_weak@VERSION
     3: 0000000000001040    24 FUNC    LOCAL  DEFAULT    14 c2pa_local
     4: 0000000000001060    24 FUNC    GLOBAL HIDDEN     15 c2pa_hidden
     5: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND c2pa_undefined
     6: 0000000000001080     8 OBJECT  GLOBAL DEFAULT    16 c2pa_object
     7: 00000000000010a0    24 FUNC    GLOBAL DEFAULT     0 c2pa_zero_ndx
     8: 00000000000010c0    24 FUNC    GLOBAL DEFAULT    17 unrelated_symbol
"""
        self.assertEqual(
            qualification.parse_elf_exported_symbols(text),
            {"c2pa_global", "c2pa_weak"},
        )

    def test_windows_export_parser_accepts_only_export_table_entries(self):
        text = """
Export {
  Name: _c2pa_exported
  RVA: 0x123
}
Symbol {
  Name: c2pa_not_exported
  Section: .text
}
"""
        self.assertEqual(
            qualification.parse_coff_exported_symbols(text), {"c2pa_exported"}
        )

    def test_generated_header_requires_marker_version_and_all_exports(self):
        version = qualification.workspace_version(ROOT / "Cargo.toml")
        qualification._validate_header_bytes(_valid_header_bytes(), version)
        invalid = _valid_header_bytes().replace(
            qualification.REQUIRED_SYMBOLS[0].encode("ascii"), b"missing_symbol"
        )
        with self.assertRaisesRegex(ValueError, "missing declarations"):
            qualification._validate_header_bytes(invalid, version)
        wrong_version = _valid_header_bytes().replace(
            version.encode("ascii"), b"0.0.0-wrong"
        )
        with self.assertRaisesRegex(ValueError, "does not match workspace version"):
            qualification._validate_header_bytes(wrong_version, version)

    def test_header_comment_mentions_do_not_count_as_prototypes(self):
        version = qualification.workspace_version(ROOT / "Cargo.toml")
        symbol = qualification.REQUIRED_SYMBOLS[0]
        line = f"C2PA_API extern int {symbol}(void);"
        line_comment_only = (
            _valid_header_bytes().decode("utf-8").replace(line, f"// {line}")
        )
        with self.assertRaisesRegex(ValueError, re.escape(symbol)):
            qualification._validate_header_bytes(
                line_comment_only.encode("utf-8"), version
            )
        block_comment_only = (
            _valid_header_bytes().decode("utf-8").replace(line, f"/* {line} */")
        )
        with self.assertRaisesRegex(ValueError, re.escape(symbol)):
            qualification._validate_header_bytes(
                block_comment_only.encode("utf-8"), version
            )

    def test_required_exports_exist_in_actual_ffi_sources(self):
        source = "\n".join(
            (ROOT / relative).read_text(encoding="utf-8")
            for relative in ("c2pa_c_ffi/src/c_api.rs", "c2pa_c_ffi/src/live_video.rs")
        )
        self.assertEqual(len(qualification.REQUIRED_SYMBOLS), 13)
        self.assertEqual(
            len(set(qualification.REQUIRED_SYMBOLS)),
            len(qualification.REQUIRED_SYMBOLS),
        )
        for symbol in qualification.REQUIRED_SYMBOLS:
            with self.subTest(symbol=symbol):
                self.assertRegex(
                    source, rf"extern\s+\"C\"\s+fn\s+{re.escape(symbol)}\s*\("
                )

    def test_package_manifests_features_and_crypto_profiles_are_real(self):
        for kind in ("sdk", "ffi", "c2patool"):
            package, manifest, features, _, _ = qualification.feature_configuration(
                kind
            )
            data = tomllib.loads((ROOT / manifest).read_text(encoding="utf-8"))
            self.assertEqual(data["package"]["name"], package)
            for feature in features:
                with self.subTest(package=package, feature=feature):
                    self.assertIn(feature, data["features"])
        sdk = tomllib.loads(
            (ROOT / qualification.SDK_MANIFEST).read_text(encoding="utf-8")
        )
        cli = tomllib.loads(
            (ROOT / qualification.TOOL_MANIFEST).read_text(encoding="utf-8")
        )
        self.assertEqual(sdk["package"]["rust-version"], qualification.TOOLCHAIN)
        self.assertEqual(cli["features"]["default"], ["networking"])
        self.assertIn("openssl", cli["dependencies"]["c2pa"]["features"])
        openssl = sdk["target"]['cfg(not(target_arch = "wasm32"))']["dependencies"][
            "openssl"
        ]
        self.assertIn("vendored", openssl["features"])


class WorkflowTests(unittest.TestCase):
    def test_workflow_cargo_commands_exactly_match_recorded_commands(self):
        text = WORKFLOW.read_text(encoding="utf-8")
        for target in qualification.SUPPORTED_TARGETS:
            with self.subTest(target=target):
                self.assertEqual(
                    _normalized_workflow_cargo_commands(text, target),
                    qualification.cargo_commands(target),
                )
        self.assertEqual(text.count(" command-manifest "), 1)
        self.assertIn('--command-manifest "$commands"', text)
        self.assertNotRegex(text, r"\beval\b")

    def test_dedicated_workflow_has_pins_matrix_timeouts_and_release_guards(self):
        text = WORKFLOW.read_text(encoding="utf-8")
        try:
            import yaml
        except ImportError:
            workflow = None
        else:
            workflow = yaml.safe_load(text)
            self.assertIsInstance(workflow, dict)

        self.assertIn("feat/live-video-vsi", text)
        self.assertIn('"castlabs-live-video-v*"', text)
        self.assertIn("workflow_dispatch:", text)
        self.assertNotIn("pull_request_target:", text)
        self.assertIn('python-version: "3.12"', text)
        self.assertEqual(text.count("actions/setup-python@"), 2)
        self.assertIn("toolchain: 1.88.0", text)
        self.assertIn("toolchain: nightly-2026-01-16", text)
        self.assertIn("cargo +nightly-2026-01-16 fmt --all -- --check", text)
        self.assertIn('CARGO_BUILD_JOBS: "1"', text)
        self.assertIn("timeout-minutes: 240", text)
        self.assertIn("timeout-minutes: 30", text)
        self.assertNotIn("continue-on-error", text)
        self.assertNotIn("if: always()", text)
        self.assertNotIn("--clobber", text)
        self.assertNotIn("--generate-notes", text)
        self.assertIn("needs: qualify", text)
        self.assertIn("github.event_name == 'push'", text)
        self.assertIn("github.event_name == 'workflow_dispatch'", text)
        self.assertIn("github.ref_type == 'tag'", text)
        self.assertIn("GITHUB_REF_TYPE", text)
        self.assertIn("git show-ref --verify", text)
        self.assertIn("Release tag must contain a valid version", text)
        self.assertIn("github.ref_protected", text)
        self.assertIn("CASTLABS_GITHUB_IMMUTABLE_RELEASES_ENABLED", text)
        self.assertIn("The workflow cannot verify that repository setting", text)
        self.assertIn("attestations: write", text)
        self.assertIn("verify-symbols", text)
        self.assertIn("verify-header", text)
        self.assertIn("verify-c2patool-help", text)
        self.assertIn("verify-release-assets", text)
        self.assertIn("target/${{ matrix.target }}/release/c2pa.h", text)
        self.assertIn("c2pa_c.dll.lib", text)
        self.assertIn("gh release upload", text)
        self.assertIn("--draft=false", text)
        self.assertIn("trap cleanup_draft EXIT", text)
        self.assertIn("If this is a stale draft", text)
        self.assertIn('--notes "Castlabs fork live-video qualification', text)
        self.assertIn("--manifest-path sdk/Cargo.toml", text)
        self.assertIn("--manifest-path c2pa_c_ffi/Cargo.toml", text)
        self.assertIn("--manifest-path cli/Cargo.toml", text)
        self.assertRegex(
            text,
            r"cargo \+1\.88\.0 test --locked --manifest-path cli/Cargo\.toml.*--features",
        )
        for action_ref in re.findall(r"uses:\s*([^\s#]+)", text):
            with self.subTest(action=action_ref):
                self.assertRegex(action_ref, r"^[^@]+@[0-9a-f]{40}$")

        if workflow is not None:
            triggers = workflow.get("on", workflow.get(True))
            self.assertEqual(
                triggers["pull_request"]["branches"], ["feat/live-video-vsi"]
            )
            self.assertEqual(triggers["push"]["branches"], ["feat/live-video-vsi"])
            self.assertEqual(triggers["push"]["tags"], ["castlabs-live-video-v*"])
            self.assertIn("workflow_dispatch", triggers)
            self.assertEqual(workflow["permissions"], {"contents": "read"})
            self.assertEqual(workflow["env"]["CARGO_BUILD_JOBS"], "1")
            self.assertEqual(
                workflow["env"]["SDK_FEATURES"], ",".join(qualification.SDK_FEATURES)
            )
            self.assertEqual(
                workflow["env"]["FFI_FEATURES"], ",".join(qualification.FFI_FEATURES)
            )
            self.assertEqual(
                workflow["env"]["TOOL_FEATURES"], ",".join(qualification.TOOL_FEATURES)
            )
            qualify = workflow["jobs"]["qualify"]
            self.assertEqual(qualify["timeout-minutes"], 240)
            matrix = qualify["strategy"]["matrix"]["include"]
            self.assertEqual(
                {entry["target"] for entry in matrix},
                set(qualification.SUPPORTED_TARGETS),
            )
            by_target = {entry["target"]: entry for entry in matrix}
            self.assertEqual(
                by_target["x86_64-pc-windows-msvc"]["import_library"],
                "c2pa_c.dll.lib",
            )
            self.assertEqual(
                by_target["x86_64-unknown-linux-gnu"]["import_library"], ""
            )
            release = workflow["jobs"]["release"]
            self.assertEqual(release["needs"], "qualify")
            self.assertEqual(release["timeout-minutes"], 30)
            self.assertEqual(release["environment"], "castlabs-live-video-release")
            release_condition = release["if"]
            self.assertIn("github.event_name == 'push'", release_condition)
            self.assertIn("github.ref_type == 'tag'", release_condition)
            self.assertIn("github.event_name == 'workflow_dispatch'", release_condition)
            self.assertIn("inputs.publish_release == true", release_condition)
            self.assertIn("inputs.release_tag", release["env"]["RELEASE_TAG"])
            self.assertEqual(
                release["permissions"],
                {"contents": "write", "attestations": "write", "id-token": "write"},
            )
            for job_name in ("qualify", "release"):
                steps = workflow["jobs"][job_name]["steps"]
                setup_indices = [
                    index
                    for index, step in enumerate(steps)
                    if str(step.get("uses", "")).startswith("actions/setup-python@")
                ]
                self.assertEqual(len(setup_indices), 1)
                first_python_run = min(
                    index
                    for index, step in enumerate(steps)
                    if "python " in str(step.get("run", ""))
                )
                self.assertLess(setup_indices[0], first_python_run)


class DocumentationTests(unittest.TestCase):
    def test_controls_are_explicitly_fork_only(self):
        qualification_doc = QUALIFICATION_DOC.read_text(encoding="utf-8")
        experimental_doc = EXPERIMENTAL_DOC.read_text(encoding="utf-8")
        for text in (qualification_doc, experimental_doc):
            self.assertIn("Castlabs fork", text)
            self.assertIn("not a proposal for upstream disposition", text)
        self.assertIn(
            "workflow files present on the repository's default branch",
            qualification_doc,
        )
        self.assertIn("tagged feature commit", qualification_doc)
        self.assertIn("CASTLABS_GITHUB_IMMUTABLE_RELEASES_ENABLED", qualification_doc)
        self.assertIn(
            "explicit operator attestation, not automated proof", qualification_doc
        )


if __name__ == "__main__":
    unittest.main()
